### ISSUE TITLE
zephyr deposit not generating

### ISSUE THREAD

**Issue by broz21** [AquexTheSeal/Celestisynth#12]

**Comment by AquexTheSeal** [comment]
Zephyr deposits aren't that common so try looking further. And please check if you are on the latest version of the mod!

**Comment by Krzear** [comment]
I'd say maybe make it more common as biomes that are high enough to spawn them in the first place can either be pretty rare, or less so depending on your seed, on top of the odds of it spawning where conditions are right. I went through many different places high enough, making it around 8000 blocks from spawn without coming across one

**Comment by broz21** [comment]
yeah i explored like 25 jagged peaks, snowy slopes and groves biomes without seeing one single deposit

**Comment by broz21** [comment]
and could i make it more common myself?

**Comment by AquexTheSeal** [comment]
> yeah i explored like 25 jagged peaks, snowy slopes and groves biomes without seeing one single deposit

hmmm, seems odd. I will try to fix this

**Comment by AquexTheSeal** [comment]
Fixed in 1.19.2 Full Release
