### ISSUE TITLE
Dying whist Right-clicking with Crescentia Bricks Your World

### ISSUE THREAD

**Issue by Krzear** [AquexTheSeal/Celestisynth#13]
There's a big problem with this mod that cause your world to brick permanently. Whenever you die in the middle of using your right click with the Crescentia, the game doesn't let you die and instead finishes the animation leaving you in a dead state, without the re-spawn screen, you cannot use chat or commands, or even the pause menu to get out of this, restarting minecraft and reloading the world will have the sound FX in the background, but will never finish loading back into the world (I've also put this on Github too) https://youtu.be/te4r32m7W6c

**Comment by AquexTheSeal** [comment]
Thank you for your report! I will definitely look into this. May I ask if it had happened to other weapon skills?

**Comment by Krzear** [comment]
I died via fall damage with the Solaris and nothing broke, not up to testing the Breeze Breaker yet, so I'll let you know there if anything breaks for me

**Comment by AquexTheSeal** [comment]
Fixed in 1.19.2 Full Release
