### ISSUE TITLE
[Suggestion] Add config (perhaps) for disabling or lessening slash effects on first person view

### ISSUE THREAD

**Issue by KamiSami** [AquexTheSeal/Celestisynth#2]
Just happened to notice it is pretty hard to see what you are hitting due to all effects going on, so it might be handy that user who do this either has no effects shown on first person view or at least lessened, would this be something you'd consider? I mean, it's not super badly in the way, but sometimes can be bit of problem, not always though.

**Comment by AquexTheSeal** [comment]
Sounds like a great idea! I'll see what I can do! 👌

**Comment by AquexTheSeal** [comment]
That configuration option will be added in the next update under the `celestisynth/client.toml` file! (Unfortunately, I haven't found a workaround for it to work on servers at the moment)

Thank you for the suggestion!
