### ISSUE TITLE
Item sometimes randomly be tagged with csController NBT tag

### ISSUE THREAD

**Issue by Snow5Wolf** [AquexTheSeal/Celestisynth#20]
Sometimes some items randomly got tagged with this NBT tags make them unstackable with other items which is very annoying.
I also found somes code in debug.log and lastest.log that might be related
debug.log : 
`[15thg 82023 15:18:50.460] [Server thread/DEBUG] [net.minecraftforge.common.ForgeHooks/WP]: Gathering id map for writing to world save csController tag test
[15thg 82023 15:18:50.469] [Server thread/DEBUG] [net.minecraftforge.common.ForgeHooks/WP]: ID Map collection complete csController tag test`
latest.log :
`[15thg 82023 15:18:50.422] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[csController tag test]'/minecraft:overworld
[15thg 82023 15:18:50.449] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[csController tag test]'/minecraft:the_nether
[15thg 82023 15:18:50.454] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[csController tag test]'/minecraft:the_end`
Mods list :
bettercombat-forge-1.7.1+1.19
celestisynth-1.19.2-1.0.1
cloth-config-8.3.103-forge
Cucumber-1.19.2-6.0.7
ferritecore-5.0.3-forge
FpsReducer2-forge-1.19.2-2.1
geckolib-forge-1.19-3.1.40
player-animation-lib-forge-1.0.2
OptiFine_1.19.2_HD_U_I2
![image](https://github.com/AquexTheSeal/Celestisynth/assets/122160112/7b261805-728b-4366-994b-83dad61ae863)

**Comment by AquexTheSeal** [comment]
did you do anything that could potentially cause this problem?

**Comment by KhanhPham05** [comment]
[For English, please refer below]
[Vietnamese here]
Vâng, tác giả đã fix trong code rồi, và tác giả cũng sẽ fix lại những nhãn dư thừa kia trong những bản update sau. Sau khi update và đăng nhập vào thế giới thì bn sẽ có thể stack lại các item bị lỗi với nhau.

[English]
Yes, the author has fixed it in dev, and he is also fix those redundant items tags in future patch builds. These vanilla items should be stack again after you update the mod and login your world.
