### ISSUE TITLE
Cannot invoke "java.util.function.Predicate.test(Object)" because "isAmmo" is null

### ISSUE THREAD

**Issue by KevzCz** [AquexTheSeal/Celestisynth#23]
[crash-2023-08-19_01.46.56-client.txt](https://github.com/AquexTheSeal/Celestisynth/files/12383218/crash-2023-08-19_01.46.56-client.txt)

Scrolling to Rainfall Serenity will crash the game.

Tried to see what could've cause the crash with Not Enough Crashes and it seems that Supplementaries is the cause but could also be wrong.

**Comment by KhanhPham05** [comment]
Sorry for late response, but did you try reproducing the bug with only this mod and no other additional mods ?!

**Comment by KevzCz** [comment]
Ah I forgot to close the issue. The crashes stopped in the newest update so thanks! :"Đ
