### ISSUE TITLE
Crash when joining a multiplayer world

### ISSUE THREAD

**Issue by 2Sloow** [AquexTheSeal/Celestisynth#24]
With my friends we use a modpack which contains the "essential mod" to be able to play together.
the game crashes when we try to join a world (we all have the Celestisynth mod installed)

![image](https://github.com/AquexTheSeal/Celestisynth/assets/143907774/6ae13104-7cff-4882-8d4a-c4568387da97)

**Comment by AquexTheSeal** [comment]
Closing this issue just to organize other mod issues. Feel free to re-open this issue if you need to!
