### ISSUE TITLE
Items Don't Stack After Taking Damage

### ISSUE THREAD

**Issue by Brimstone287** [AquexTheSeal/Celestisynth#25]
Regardless of vanilla or modded item, anytime you take damage while holding an item in your hand, the item value changes and either no longer functions correctly or does not stack (ex. if you're holding cobblestone and take damage from a zombie, every cobblestone you pick up after that won't stack with the ones you were holding). Only workaround I was able to find is placing all the items being held if it was a block and regathering them but with items it makes them change in a way that doesn't let them be used the same. Hopefully that information helps somewhat it was everything I could gather after discovering that mod was the issues out of the ones I was using.

**Comment by Luviam** [comment]
Had this same issue, was wondering why a bunch of my items just didn't wanna stack lmfao

**Comment by Brimstone287** [comment]
It seems like the newest update fixed the issue I haven't run into it again yet. Fingers crossed it stays that way 🤞
