### ISSUE TITLE
The mod is not loading/working when i tried to play the mod and my minecraft keeps crashing and sometimes it says not working or cant load the the mod(java.lang.reflect.InvocationTargetException: null)

### ISSUE THREAD

**Issue by YUNISHAKAKI** [AquexTheSeal/Celestisynth#3]

**Comment by AquexTheSeal** [comment]
Hello! May you please send the crash log?

**Comment by Amygdal4ever** [comment]
same problem, how do i send the crash log?

**Comment by ArcaneLD** [comment]
[crash-2023-06-20_18.41.47-fml.txt](https://github.com/AquexTheSeal/Celestisynth/files/11803596/crash-2023-06-20_18.41.47-fml.txt)
Here's my crash report, same problem
Every version of your mod seems to do this so far, and if this is relevant i use MultiMC as a launcher with Forge 43.2.0

**Comment by AquexTheSeal** [comment]
> [crash-2023-06-20_18.41.47-fml.txt](https://github.com/AquexTheSeal/Celestisynth/files/11803596/crash-2023-06-20_18.41.47-fml.txt) Here's my crash report, same problem Every version of your mod seems to do this so far, and if this is relevant i use MultiMC as a launcher with Forge 43.2.0

Make sure you have the required dependencies installed. Seems like you didn't have PlayerAnimator installed yet :V
Thanks for reminding me to add a dependency missing screen though!
