### ISSUE TITLE
# Issue: Celestial Crafting Table JSON Pattern Deviation

### ISSUE THREAD

**Issue by ViMayer** [AquexTheSeal/Celestisynth#31]
**Issue: Celestial Crafting Table JSON Pattern Deviation**

**Description:**
The Celestial Crafting Table JSON configuration deviates from the standard Minecraft pattern practice. While creating custom recipes using datapacks, I encountered an inconsistency in the handling of the "pattern" field.

**Example:**
Consider the pattern field for a diamond helmet in the default Minecraft crafting table recipe, where each row inside the pattern field corresponds to a row in the crafting table:
```json
{
    "pattern": [
      "ddd",
      "d d"
    ]
}
```

In standard Minecraft crafting table recipes, if a pattern row is empty, there is no need to place an item in that row for the recipe to work. However, in the Celestial Crafting Table recipe, leaving a row empty renders the recipe non-functional.

This behavior may lead to challenges for consistent recipe creation.

**Expected Behavior:**
Align the Celestial Crafting Table JSON pattern handling with the default Minecraft crafting table pattern practice. Empty rows in the pattern field should not impact the functionality of the recipe.

*This observation is based on the current behavior as of 1.19.2-1.1.3 with forge version 43.2.0*

**Comment by AquexTheSeal** [comment]
Hello, thank you for the report! I have started taking a look onto this issue after I released version 1.1.4 and 1.1.5 and it seems like it's all good on my end. Try out the new version and see if it has fixed the issue for you.

![image](https://github.com/AquexTheSeal/Celestisynth/assets/85479639/96867e18-6a13-4c8b-a553-39065dc5a0b8)
![image](https://github.com/AquexTheSeal/Celestisynth/assets/85479639/816a27e6-b8b1-4128-9555-b0c9bcc3a272)

**Comment by AquexTheSeal** [comment]
Closing this issue just to organize other mod issues. Feel free to re-open this issue if you need to!
