### ISSUE TITLE
Incompatibility with Passive Skill Tree 1.19.2

### ISSUE THREAD

**Issue by Owls-Parliament** [AquexTheSeal/Celestisynth#33]
While using the Rainfall Serenity bow, the game crashed. Not Enough Crashes (https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge) identified Passive Skill Tree (https://www.curseforge.com/minecraft/mc-mods/passive-skill-tree) to be the culprit (after I eliminated the other mods to which it pointed), though it is possible that it is on the end of Celestisynth. Either way, the bow only crashed when an entity was hit, but not if it hit a block. As soon as any entity was hit, the game immediately crashed.
I have sent a copy of this crash to the creator of Passive Skill Tree as well. (https://github.com/Daripher/Passive-Skill-Tree/issues/101)
After removing Passive Skill Tree, the Rainfall Serenity worked correctly.
[crash-2023-12-14_21.40.23-client.txt](https://github.com/AquexTheSeal/Celestisynth/files/13680717/crash-2023-12-14_21.40.23-client.txt)

**Comment by Daripher** [comment]
I think in one of your arrow entities `ItemStack getPickupItem()` returns `null`. This shouldn't happen, you should use `ItemStack.EMPTY` instead.

**Comment by AquexTheSeal** [comment]
> I think in one of your arrow entities `ItemStack getPickupItem()` returns `null`. This shouldn't happen, you should use `ItemStack.EMPTY` instead.

Will try to patch this for the next update! Thank you for the report!

**Comment by AquexTheSeal** [comment]
Fixed!
