### ISSUE TITLE
[1.20.1] Server basically Ddossing the client

### ISSUE THREAD

**Issue by Luviam** [AquexTheSeal/Celestisynth#36]
In short, my server is sending loads of data to the client (me) and making the game basically unplayable on my server.
I'm on 1.20.1 with forge version 47.2.19 with the latest versions of CelestiSynth, GeckoLib, and PlayerAnimator.
[latest.log](https://github.com/AquexTheSeal/Celestisynth/files/14270930/latest.log)

Also here's a video showcasing it visually to give a better understanding.
https://youtu.be/IHx2U2fTT3U

**Comment by AquexTheSeal** [comment]
Whoah, what a really surprising one. I'll check into this! 

Thank you so much for the report though!

**Comment by ChapperNi** [comment]
Omg this happened to my friend earlier today, we had to uninstall for the time being. Actually insane that its a technical DDOS!

**Comment by AquexTheSeal** [comment]
> Omg this happened to my friend earlier today, we had to uninstall for the time being. Actually insane that its a technical DDOS!

I'm guessing that Celestisynth is cotinuously sending too much packets to the server at once, hence causing the internet issues. I'll investigate further into it.
