### ISSUE TITLE
Weapons bug with shaders

### ISSUE THREAD

**Issue by Kayron3** [AquexTheSeal/Celestisynth#38]
Idk if its my gpu or shaders but all weapons get so bright it turns just white

**Comment by AquexTheSeal** [comment]
Yeah I still plan on patching that up!

**Comment by Lisovsky-UwU** [comment]
The problem still hasn't been fixed?
Very hard on the eyes when playing with shaders

**Comment by RaveTr** [comment]
Fixed for next update.
