### ISSUE TITLE
Brightest Sh-t ive seen xD

### ISSUE THREAD

**Issue by AnomalousDeity** [AquexTheSeal/Celestisynth#40]
nothing big other than with shaders its the most brightest weapons Ive ever held, 10/10 gives me advantage at combat by blinding my enemies! xD love the weapons btw!

![2024-02-25_00 08 57](https://github.com/AquexTheSeal/Celestisynth/assets/91780401/cc846bbd-5dc9-4a92-9131-926aacbb1796)

**Comment by AquexTheSeal** [comment]
shining brighter than the sun for sure 💀

Don't worry, this issue has already been reported and a fix is coming next update!
