### ISSUE TITLE
A strange "- " character appears at the beginning of the description of the skill "Lunar Celebration Barrage"

### ISSUE THREAD

**Issue by NitsugaoO** [AquexTheSeal/Celestisynth#9]
I noticed a strange "- " character appearing at the beginning of the description of the skill "Lunar Celebration Barrage", whether playing in English or Chinese, while other descriptions do not.

![image](https://github.com/AquexTheSeal/Celestisynth/assets/107701680/063135d0-efa7-43a8-a80b-671d2801cdf1) ![image](https://github.com/AquexTheSeal/Celestisynth/assets/107701680/7ac7b1d0-c069-4f26-b23b-126f0d887337)

**Comment by NitsugaoO** [comment]
Mod Version : [Forge] 1.19.4-1.0.0-beta-v6

**Comment by NitsugaoO** [comment]
By the way, on the CurseForge page, the description of Breezebreaker is the same as that of Crescentia.
![image](https://github.com/AquexTheSeal/Celestisynth/assets/107701680/dde6003d-1ee4-426a-a5c7-5b7899b9b4df)

**Comment by AquexTheSeal** [comment]
All fixed now!
